steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - 'europe-west1-docker.pkg.dev/adv-lighthouse-plnv/cloud-run-source-deploy/sunidhinaikkpmg-hue-plan-navigator/plan-navigator-git-latest:$COMMIT_SHA'
      - ./backend

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west1-docker.pkg.dev/adv-lighthouse-plnv/cloud-run-source-deploy/sunidhinaikkpmg-hue-plan-navigator/plan-navigator-git-latest:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - plan-navigator-git-latest
      - '--image=europe-west1-docker.pkg.dev/adv-lighthouse-plnv/cloud-run-source-deploy/sunidhinaikkpmg-hue-plan-navigator/plan-navigator-git-latest:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/adv-lighthouse-plnv/cloud-run-source-deploy/sunidhinaikkpmg-hue-plan-navigator/plan-navigator-git-latest:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
